version: '3'
services: 
  database:
    image: postgres:latest
    network_mode: bridge
    container_name: cm_database
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=spring
      - POSTGRES_DB=contacts_manager
  application:
    image: danielsena04/contacts-importer
    container_name: cm_application
    network_mode: bridge
    expose: 
      - 8080
    ports: 
      - 8080:8080
    restart: unless-stopped
    depends_on: 
      - database
    links: 
      - database
volumes: 
  postgres-data: