spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts_manager
    username: spring
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    initialize-schema: always