spring:
  datasource:
    url: jdbc:h2:mem:contacts_manager
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    initialize-schema: always